apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: image
  replicas: 1
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: image:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicioimage
  namespace: ingress-nginx
spec:
  ports:
    - protocol: "TCP"
      port: 8080        # The port inside the cluster
      targetPort: 8080  # The port exposed by the service
  type: NodePort        # Type of service
  selector:
          app: image


